services:
  train:
    container_name: "lunar-lander-pt"
    build: .
    tty: true
    shm_size: "4gb"
    volumes:
      - ./:/workspace
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [utility, compute, video]
